###Crear un cliente especifico
POST http://localhost:5000/cliente
content-type: application/json

{
    
    "nombre": "Esteba",
    "Apellido":"Quito",
    "email":"estebanQuito@gmail.com"    
}

###
GET http://localhost:5000/cliente



###Crear un cliente especifico
DELETE  http://localhost:5000/cliente/1

